# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Blazing fast GitHub Pages deploys
        # You may pin to the exact commit or the version.
        # uses: alex-page/blazing-fast-gh-pages-deploy@cd954d31df85a309bb5aa4a0a67cc2ac3512d722
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          # The personal access token secret can be passed in using {{ secrets.GH_PAT }}
          #repo-token: {{ secrets.GH_PAT }}
          # The directory for the built website
          site-directory: . # default is _site
          # The branch to deploy the built website to
          #deploy-branch: # default is gh-pages
          # The commit message for the branch
          #commit-message: # optional, default is Deployed using Blazing fast GitHub Pages deploy
